"""empty message

Revision ID: 349b93b0de1e
Revises: d0322ffc50f5
Create Date: 2020-07-10 20:20:02.865623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349b93b0de1e'
down_revision = 'd0322ffc50f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('badge_number', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('last_name')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=120), nullable=False),
    sa.Column('id_number', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('date'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('id_number'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('diagnostic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('covidtest', sa.String(length=120), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('reasonforadmi', sa.String(length=120), nullable=False),
    sa.Column('symptoms', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.String(length=120), nullable=False),
    sa.Column('prescription', sa.String(length=120), nullable=False),
    sa.Column('total_cost', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('covidtest'),
    sa.UniqueConstraint('notes'),
    sa.UniqueConstraint('prescription'),
    sa.UniqueConstraint('reasonforadmi'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('symptoms'),
    sa.UniqueConstraint('total_cost')
    )
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('diagnostic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=120), nullable=False),
    sa.Column('room_number', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.String(length=120), nullable=False),
    sa.Column('end_date', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('end_date'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('room_number'),
    sa.UniqueConstraint('start_date'),
    sa.UniqueConstraint('status')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment')
    op.drop_table('specialty')
    op.drop_table('diagnostic')
    op.drop_table('patient')
    op.drop_table('doctor')
    # ### end Alembic commands ###
