"""empty message

Revision ID: ceee5bf92263
Revises: 364d861dca06
Create Date: 2020-07-30 13:41:28.771626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceee5bf92263'
down_revision = '364d861dca06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnostic', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diagnostic', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagnostic', type_='foreignkey')
    op.drop_column('diagnostic', 'patient_id')
    # ### end Alembic commands ###
