"""empty message

Revision ID: ecacd3c3fb0b
Revises: 0a8e27385fe5
Create Date: 2020-07-24 02:44:02.399388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecacd3c3fb0b'
down_revision = '0a8e27385fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialty')
    op.alter_column('diagnostic', 'covidtest',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('diagnostic', 'notes',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('diagnostic', 'prescription',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('diagnostic', 'reasonforadmi',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('diagnostic', 'status',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('diagnostic', 'symptoms',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('diagnostic', 'total_cost',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('covidtest', table_name='diagnostic')
    op.drop_index('notes', table_name='diagnostic')
    op.drop_index('prescription', table_name='diagnostic')
    op.drop_index('reasonforadmi', table_name='diagnostic')
    op.drop_index('status', table_name='diagnostic')
    op.drop_index('symptoms', table_name='diagnostic')
    op.drop_index('total_cost', table_name='diagnostic')
    op.alter_column('doctor', 'first_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('doctor', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('badge_number', table_name='doctor')
    op.drop_index('first_name', table_name='doctor')
    op.drop_index('last_name', table_name='doctor')
    op.drop_column('doctor', 'badge_number')
    op.alter_column('patient', 'address',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patient', 'date',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patient', 'first_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patient', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patient', 'id_number',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patient', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('patient', 'phone_number',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('address', table_name='patient')
    op.drop_index('date', table_name='patient')
    op.drop_index('first_name', table_name='patient')
    op.drop_index('gender', table_name='patient')
    op.drop_index('id_number', table_name='patient')
    op.drop_index('last_name', table_name='patient')
    op.drop_index('phone_number', table_name='patient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone_number', 'patient', ['phone_number'], unique=True)
    op.create_index('last_name', 'patient', ['last_name'], unique=True)
    op.create_index('id_number', 'patient', ['id_number'], unique=True)
    op.create_index('gender', 'patient', ['gender'], unique=True)
    op.create_index('first_name', 'patient', ['first_name'], unique=True)
    op.create_index('date', 'patient', ['date'], unique=True)
    op.create_index('address', 'patient', ['address'], unique=True)
    op.alter_column('patient', 'phone_number',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('patient', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('patient', 'id_number',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('patient', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('patient', 'first_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('patient', 'date',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('patient', 'address',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.add_column('doctor', sa.Column('badge_number', mysql.VARCHAR(length=120), nullable=True))
    op.create_index('last_name', 'doctor', ['last_name'], unique=True)
    op.create_index('first_name', 'doctor', ['first_name'], unique=True)
    op.create_index('badge_number', 'doctor', ['badge_number'], unique=True)
    op.alter_column('doctor', 'last_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('doctor', 'first_name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_index('total_cost', 'diagnostic', ['total_cost'], unique=True)
    op.create_index('symptoms', 'diagnostic', ['symptoms'], unique=True)
    op.create_index('status', 'diagnostic', ['status'], unique=True)
    op.create_index('reasonforadmi', 'diagnostic', ['reasonforadmi'], unique=True)
    op.create_index('prescription', 'diagnostic', ['prescription'], unique=True)
    op.create_index('notes', 'diagnostic', ['notes'], unique=True)
    op.create_index('covidtest', 'diagnostic', ['covidtest'], unique=True)
    op.alter_column('diagnostic', 'total_cost',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('diagnostic', 'symptoms',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('diagnostic', 'status',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('diagnostic', 'reasonforadmi',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('diagnostic', 'prescription',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('diagnostic', 'notes',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('diagnostic', 'covidtest',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_table('specialty',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], name='specialty_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
